"""A FRESHLY SCAFFOLDED REPOSITORY VALIDATES CLEAN — AT BOTH RELEASES.

add-binding-consumer-identity §6.2. The two-release form is what makes the
difference visible, and the test is RUN rather than asserted: the repository is
generated by the real `scripts/apply-domain-starter.py` and the real validator
is pointed at its bytes.

WHY BOTH RELEASES. Three drafts of the generator instruction converged, and the
last two were each wrong at one end:

  draft 1  emit the block in the template's own `<placeholder>` style
           -> FAILS at the minor: the placeholder fails the identifier grammar,
              so a scaffolded repo would warn on day one.
  draft 2  emit no block at all
           -> FAILS at the major: a missing block is an ERROR there and the stub
              token is the only exemption, so every new domain repository would
              break on the upgrade.
  draft 3  emit `consumer: {instantiation_stub: true}`
           -> clean at BOTH, which is what this file measures.

A ONE-RELEASE ASSERTION WOULD HAVE PASSED FOR DRAFT 2 AND SHIPPED IT. That is
the whole reason the assertion is written in this shape.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest
import yaml
from jsonschema import Draft202012Validator

from major_projection import load_minor_schema, project_major_schema

ROOT = Path(__file__).resolve().parents[2]
STARTER = ROOT / "scripts" / "apply-domain-starter.py"
VALIDATOR = ROOT / "scripts" / "validate-credential-contracts.py"
KINDS = {
    "xfactory_credential_requirements",
    "xfactory_runtime_capability_grant_template",
    "xfactory_credential_binding_template",
    "xfactory_credential_broker_contract",
    "xfactory_credential_audit_policy",
}


def _validator_module():
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "credential_contracts_validator_scaffold", VALIDATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


V = _validator_module()


@pytest.fixture(scope="module")
def scaffolded_repo(tmp_path_factory):
    target = tmp_path_factory.mktemp("scaffolded-domain")
    result = subprocess.run(
        [sys.executable, str(STARTER), str(target),
         "--domain-id", "probex", "--product-name", "ProbexFactory"],
        capture_output=True, text=True, check=False)
    assert result.returncode == 0, result.stdout + result.stderr
    assert (target / "credentials/bindings.template.yaml").is_file()
    return target


def _credential_docs(repo: Path):
    for path in sorted((repo / "credentials").rglob("*.y*ml")):
        doc = yaml.safe_load(path.read_text())
        if isinstance(doc, dict) and doc.get("kind") in KINDS:
            yield path, doc


def test_the_generator_emits_the_stub_token_and_nothing_else(scaffolded_repo):
    """Not a placeholder, which fails the grammar; not an omission, which cannot
    stay clean at the major. The token asserts only that the record is a stub,
    which is exactly true of a file written before any install exists."""
    doc = yaml.safe_load((scaffolded_repo / "credentials/bindings.template.yaml").read_text())
    for binding in doc["credential_bindings"].values():
        assert binding["consumer"] == {"instantiation_stub": True}


def test_the_scaffolded_repo_is_clean_at_the_introducing_minor(scaffolded_repo):
    """The REAL validator over the generator's OWN emitted bytes — zero errors
    and, because a warning here is a break on the upgrade, zero warnings."""
    result = subprocess.run([sys.executable, str(VALIDATOR), str(scaffolded_repo)],
                            capture_output=True, text=True, check=False)
    assert result.returncode == 0, result.stdout + result.stderr
    assert "0 warning(s)" in result.stdout, result.stdout
    assert "WARN" not in result.stdout, result.stdout


def test_the_scaffolded_repo_is_clean_at_the_major(scaffolded_repo):
    """The major is the projected schema PLUS the eight deprecation codes read
    as errors. Both halves are checked, because the two drafts this assertion
    caught failed one half each."""
    major = Draft202012Validator(project_major_schema())
    minor = Draft202012Validator(load_minor_schema())
    seen = 0
    for path, doc in _credential_docs(scaffolded_repo):
        seen += 1
        assert [e.message for e in minor.iter_errors(doc)] == [], path.name
        assert [e.message for e in major.iter_errors(doc)] == [], path.name
        assert V._deprecation_warnings(doc) == [], path.name
    assert seen >= 5, "the scaffold stopped emitting credential records"


def test_a_blockless_scaffold_would_NOT_have_stayed_clean(scaffolded_repo):
    """THE NEGATIVE CONTROL, and it is what stops the two assertions above from
    passing vacuously. Draft two — emit no block — passes the major's SCHEMA and
    is refused by its VALIDATOR, so an assertion written against the schema
    alone would have shipped it."""
    doc = yaml.safe_load((scaffolded_repo / "credentials/bindings.template.yaml").read_text())
    for binding in doc["credential_bindings"].values():
        del binding["consumer"]
    major = Draft202012Validator(project_major_schema())
    assert [e.message for e in major.iter_errors(doc)] == []
    assert [code for code, _ in V._deprecation_warnings(doc)] == ["consumer-identity-undeclared"]


def test_a_placeholder_scaffold_would_NOT_have_stayed_clean_either(scaffolded_repo):
    """Draft one, the other end: a placeholder-styled block warns on day one."""
    doc = yaml.safe_load((scaffolded_repo / "credentials/bindings.template.yaml").read_text())
    for binding in doc["credential_bindings"].values():
        binding["consumer"] = {"holder_ref": "<consuming-system>",
                               "fetch_identity": "<fetch-identity>"}
    assert "consumer-member-grammar" in [code for code, _ in V._deprecation_warnings(doc)]


def test_the_prose_template_and_the_generator_agree(scaffolded_repo):
    """`docs/domain-factory-starter-pack.md` carries the same template in prose.
    A generator and a document that disagree about the scaffolded bytes send an
    instantiator to the wrong one."""
    prose = (ROOT / "docs/domain-factory-starter-pack.md").read_text()
    assert "instantiation_stub: true" in prose
